/**:
  ros__parameters:

    # Topics
    pointCloudTopic: "/ouster/points"                   # Point cloud data
    imuTopic: "/ouster/imu"                        # IMU data (Ouster internal, 6-axis)
    odomTopic: "odometry/imu"                    # IMU pre-preintegration odometry, same frequency as IMU
    gpsTopic: "odometry/gpsz"                    # GPS odometry topic from navsat, see module_navsat.launch file

    # Frames
    lidarFrame: "os_lidar"
    baselinkFrame: "base_link"
    odometryFrame: "odom"
    mapFrame: "map"

    # GPS Settings
    useImuHeadingInitialization: false           # if using GPS data, set to "true"
    initial_heading_yaw: 0.0                     # rad, initial yaw heading value
    useGpsElevation: false                       # if GPS elevation is bad, set to "false"
    gpsCovThreshold: 2.0                         # m^2, threshold for using GPS data
    poseCovThreshold: 25.0                       # m^2, threshold for using GPS data
    gps_update_interval: 10.0                    # sec, GPS update interval
    gps_distance_threshold: 0.5                  # m, GPS distance threshold

    # Export settings
    savePCD: false                               
    savePCDDirectory: "/Downloads/LOAM/"         # in your home folder, starts and ends with "/". Warning: the code deletes "LOAM" folder then recreates it. See "mapOptimization" for implementation

    # Sensor Settings
    sensor: ouster                               # lidar sensor type, either 'velodyne', 'ouster' or 'livox'
    N_SCAN: 32                                   # number of lidar channels (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
    Horizon_SCAN: 1024                            # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
    downsampleRate: 1                            # default: 1. Downsample your data if too many
    # points. i.e., 16 = 64 / 4, 16 = 16 / 1
    lidarMinRange: 1.0                           # default: 1.0, minimum lidar range to be used
    lidarMaxRange: 1000.0                        # default: 1000.0, maximum lidar range to be used

    # IMU Settings
    imuAccNoise: 3.9939570888238808e-03
    imuGyrNoise: 1.5636343949698187e-03
    imuAccBiasN: 6.4356659353532566e-05
    imuGyrBiasN: 3.5640318696367613e-05

    imuGravity: 9.80511
    imuRPYWeight: 0.01

    extrinsicTrans:  [ 0.0,  0.0,  0.0 ]
    extrinsicRot:    [1.0,  0.0,  0.0,
                       0.0,  1.0,  0.0,
                       0.0,  0.0, 1.0 ]
    extrinsicRPY: [ 1.0,  0.0,  0.0,
                    0.0,  1.0,  0.0,
                    0.0,  0.0,  1.0 ]

    # LOAM feature threshold
    edgeThreshold: 1.0
    surfThreshold: 0.1
    edgeFeatureMinValidNum: 10
    surfFeatureMinValidNum: 100

    # voxel filter paprams
    odometrySurfLeafSize: 0.2                     # default: 0.2 
    mappingCornerLeafSize: 0.1                    # default: 0.1 
    mappingSurfLeafSize: 0.2                      # default: 0.2

    # robot motion constraint (in case you are using a 2D robot)
    z_tollerance: 1000.0                          # meters
    rotation_tollerance: 1000.0                   # radians

    # CPU Params
    numberOfCores: 4                              # number of cores for mapping optimization
    mappingProcessInterval: 0.08                  # seconds, regulate mapping frequency

    # Surrounding map
    surroundingkeyframeAddingDistThreshold: 0.3   # meters, regulate keyframe adding threshold
    surroundingkeyframeAddingAngleThreshold: 0.2  # radians, regulate keyframe adding threshold
    surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses   
    surroundingKeyframeSearchRadius: 50.0         # meters, within n meters scan-to-map optimization
    # (when loop closure disabled)

    # Map matching (Localization)
    map_matching_update_interval: 1.0             # seconds, map matching update interval
    matching_covariance_const: [0.1, 0.1, 0.01, 0.0001, 0.0001, 0.001]  # x,y,z,roll,pitch,yaw
    overlap_ratio_threshold: 0.5                  # overlap ratio threshold for initial pose estimation
    map_matching_stale_time_threshold: 20.0       # seconds, stale time threshold for map matching

    # NDT parameters
    ndt_neighbor_search_method: "DIRECT7"         # "KDTREE" or "DIRECT7" or "DIRECT1" or "DIRECT26"
    number_of_threads_ndt: 8                      # number of threads for NDT
    ndt_resolution: 1.0                           # meters, ndt resolution
    lidar_downsample_resolution: 0.2              # meters, lidar downsample resolution
